# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z035fbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/vivado_prj/Pulse_Detector_vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/vivado_prj/Pulse_Detector_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/vivado_prj/Pulse_Detector_vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/Compute_Power.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/Discrete_FIR_Filter.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/Filter.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/FilterCoef.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/FilterCoef_block.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/FilterCoef_block1.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/FilterTapSystolicWvldin.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/Local_Peak.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/MATLAB_Function.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/subFilter.v
  C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/Pulse_Detector.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/clock_constraint.xdc
set_property used_in_implementation false [get_files C:/Users/Lenovo/Desktop/proj2/HDL-Coder-Self-Guided-Tutorial-master/pulse_detector/work/hdl_prj/hdlsrc/pulse_detector_v4/clock_constraint.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Pulse_Detector -part xc7z035fbg676-1 -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Pulse_Detector.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Pulse_Detector_utilization_synth.rpt -pb Pulse_Detector_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
